const desktop=window.dailyPlanDesktop,clock=new FocusClock(),channel=new BroadcastChannel('daily-plan-floating');
const orb=document.getElementById('orb');let pointer=null,loading=false,done=0,total=0,failed=false;
orb.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointer={x:e.screenX,y:e.screenY};orb.setPointerCapture(e.pointerId);desktop?.beginOrbDrag()});
orb.addEventListener('pointerup',e=>{if(!pointer)return;const click=Math.hypot(e.screenX-pointer.x,e.screenY-pointer.y)<6;pointer=null;desktop?.endOrbDrag();if(click)desktop?.togglePanel()});
orb.addEventListener('pointercancel',()=>{pointer=null;desktop?.endOrbDrag()});orb.addEventListener('lostpointercapture',()=>{if(pointer){pointer=null;desktop?.endOrbDrag()}});
orb.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();desktop?.togglePanel()}});
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function celebrate(){orb.classList.remove('celebrate');void orb.offsetWidth;orb.classList.add('celebrate')}
function draw(){const s=clock.seconds(),status=clock.state.status;document.body.dataset.timer=status;document.body.dataset.error=String(failed);orb.querySelector('.orb__value').textContent=status==='running'?(s<60?Math.floor(s)+'s':s<3600?Math.floor(s/60)+'m':Math.floor(s/3600)+'h'):status==='paused'?'Ⅱ':total?`${done}/${total}`:'+';orb.querySelector('.orb__eyebrow').textContent=status==='running'?'FOCUS':status==='paused'?'PAUSED':'TODAY';orb.querySelector('.orb__minute').style.strokeDashoffset=60-s%60;orb.removeAttribute('title');orb.setAttribute('aria-label',failed?'Daily Plan 连接中断，打开快捷面板':status==='idle'?`打开 Daily Plan 快捷面板，今日完成 ${done}/${total}`:`打开 Daily Plan 快捷面板，${clock.state.target?.title||'自由专注'}${status==='paused'?'已暂停':'计时中'}`)}
async function refresh(){if(loading)return;loading=true;try{const d=await DailyPlanApi.getData(),tasks=d.tasks?.[todayKey()]||[];const n=tasks.filter(t=>t.done).length;if(total&&n>done)celebrate();done=n;total=tasks.length;clock.accept(d.timer);orb.querySelector('.orb__progress').style.strokeDashoffset=100-(total?done/total*100:0);failed=false}catch{failed=true}finally{loading=false;draw()}}
desktop?.onOrbState?.(s=>{document.body.dataset.side=s.side||'';document.body.dataset.collapsed=String(s.collapsed)});channel.onmessage=e=>{if(e.data==='completed')celebrate();void refresh()};document.addEventListener('visibilitychange',()=>{document.body.dataset.hidden=String(document.hidden);if(!document.hidden)refresh()});refresh();setInterval(refresh,2000);setInterval(()=>{if(!document.hidden)draw()},100);
