const completionStyles = document.createElement('link');
completionStyles.rel = 'stylesheet';
completionStyles.href = 'completion-motion.css';
document.head.append(completionStyles);

const desktop = window.dailyPlanDesktop;
const backend = window.DailyPlanApi;
const $ = id => document.getElementById(id);
const clock = new FocusClock();
const channel = new BroadcastChannel('daily-plan-floating');
const icons = {pin:'m9 3 6 0-1 6 3 3H7l3-3z M12 12v8',external:'M14 4h6v6 M20 4l-9 9 M10 5H5v14h14v-5',close:'m6 6 12 12 M18 6 6 18',plus:'M12 5v14 M5 12h14',enter:'M19 5v9H5 M9 10l-4 4 4 4',arrow:'M5 12h14 m-5-5 5 5-5 5',play:'m9 5 10 7-10 7z',check:'m5 12 4 4 10-10'};
function icon(name){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',icons[name]);s.append(p);return s}
document.querySelectorAll('[data-icon]').forEach(el=>el.append(icon(el.dataset.icon)));
let snapshot=null, activeScope='today', requestPending=false, epoch=0, polling=false, pinned=false, expandedDone=false, editing=null, completingId=null, listSignature='', toastTimer;
const drafts={today:'',todo:''};
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function formatClock(s){s=Math.floor(s);const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return (h?`${String(h).padStart(2,'0')}:`:'')+`${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function duration(s){const m=Math.floor(s/60);return m>=60?`${Math.floor(m/60)} 小时 ${m%60} 分钟`:`${m} 分钟`}
function tell(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4200)}
function connection(ok,label=ok?'已同步':'连接中断'){$('panel-sync').classList.toggle('is-error',!ok);$('panel-sync').lastElementChild.textContent=label}
function selectView(view){document.body.dataset.view=view;document.querySelectorAll('[data-view]').forEach(e=>{e.classList.toggle('is-active',e.dataset.view===view);e.setAttribute('aria-pressed',String(e.dataset.view===view))});document.querySelectorAll('[data-panel]').forEach(e=>e.classList.toggle('is-active',e.dataset.panel===view))}
function items(){return activeScope==='today'?(snapshot?.tasks?.[todayKey()]||[]):(snapshot?.goals||[]).filter(t=>t.type==='todo')}
function meta(t){return [t.pinned?'置顶':null,t.startTime?`${t.startTime}${t.endTime?'–'+t.endTime:''}`:null,t.dueDate?`${t.dueDate} 截止`:null,t.subtasks?.length?`${t.subtasks.filter(s=>s.done).length}/${t.subtasks.length} 子任务`:null,...(t.tags||[]).map(t=>'#'+t)].filter(Boolean).join(' · ')}
function renderList(force=false){
 const all=items(),signature=JSON.stringify([activeScope,all,expandedDone,completingId]);if(editing||(!force&&signature===listSignature))return;listSignature=signature;
 const list=$('panel-task-list'),oldScroll=list.scrollTop,focused=document.activeElement?.dataset.actionKey,oldRows=[...list.querySelectorAll('[data-row-id]')],oldIds=new Set(oldRows.map(e=>e.dataset.rowId)),oldRects=new Map(oldRows.map(e=>[e.dataset.rowId,e.getBoundingClientRect()]));
 const sorted=[...all].sort((a,b)=>Number(b.pinned||false)-Number(a.pinned||false)||({high:0,medium:1,low:2}[a.priority]??1)-({high:0,medium:1,low:2}[b.priority]??1)||(a.dueDate||'9999').localeCompare(b.dueDate||'9999')||(a.createdAt||0)-(b.createdAt||0));
 list.replaceChildren();
 function row(t){const r=document.createElement('div');r.className='task-row'+(t.done?' is-done':'')+(t.id===completingId?' is-completing':'');r.dataset.priority=t.priority;r.dataset.rowId=t.id;if(oldIds.has(t.id))r.style.animation='none';const check=document.createElement('button');check.className='task-check';check.dataset.actionKey='check-'+t.id;check.setAttribute('aria-label',`${t.done?'恢复':'完成'}：${t.text}`);check.setAttribute('aria-pressed',String(!!t.done));if(t.done)check.append(icon('check'));check.onclick=()=>toggleDone(t);const copy=document.createElement('button');copy.className='task-copy';copy.title='点击编辑任务';copy.dataset.actionKey='edit-'+t.id;const title=document.createElement('strong');title.textContent=t.text;const small=document.createElement('small');small.textContent=meta(t);copy.append(title);if(small.textContent)copy.append(small);copy.onclick=()=>editTask(t,copy);r.append(check,copy);if(!t.done){const play=document.createElement('button');play.className='task-play';play.dataset.actionKey='play-'+t.id;play.setAttribute('aria-label','专注：'+t.text);play.title='开始专注';play.append(icon('play'));play.onclick=()=>startTask(t);r.append(play)}list.append(r)}
 sorted.filter(t=>!t.done).forEach(row);const completed=sorted.filter(t=>t.done);
 if(!all.length){const empty=document.createElement('div');empty.className='empty';const title=document.createElement('strong');title.textContent='留一点空间，给下一件事';empty.append(title,document.createTextNode('在上方添加任务，也可以直接开始专注。'));list.append(empty)}
 if(completed.length){const b=document.createElement('button');b.className='completed-toggle';b.textContent=`已完成 · ${completed.length} ${expandedDone?'−':'＋'}`;b.setAttribute('aria-expanded',String(expandedDone));b.onclick=()=>{expandedDone=!expandedDone;renderList()};list.append(b);if(expandedDone)completed.forEach(row)}
 list.scrollTop=oldScroll;if(focused)[...list.querySelectorAll('[data-action-key]')].find(e=>e.dataset.actionKey===focused)?.focus({preventScroll:true});
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches) requestAnimationFrame(()=>{
   list.querySelectorAll('[data-row-id]').forEach(row=>{const before=oldRects.get(row.dataset.rowId);if(!before)return;const after=row.getBoundingClientRect(),dy=before.top-after.top;if(Math.abs(dy)>1)row.animate([{transform:`translateY(${dy}px)`,opacity:.72},{transform:'translateY(0)',opacity:1}],{duration:460,easing:'cubic-bezier(.22,1,.36,1)'})});
 });
}
function render(){const ts=snapshot?.tasks?.[todayKey()]||[],done=ts.filter(t=>t.done).length;$('panel-task-count').textContent=`${done}/${ts.length}`;$('panel-task-summary').textContent=ts.length?(done===ts.length?'今天的安排，都完成了':`还有 ${ts.length-done} 件事，慢慢来`):'安排好这一刻';$('day-progress').style.strokeDashoffset=100-(ts.length?done/ts.length*100:0);$('panel-date').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});renderList();renderTimer()}
function renderTimer(){const s=clock.seconds(),state=clock.state,status=state.status,active=status!=='idle';document.body.dataset.timer=status;const value=formatClock(s);$('panel-timer-value').textContent=value;$('panel-timer-value').classList.toggle('long',s>=3600);$('panel-timer-mini').textContent=value;$('mini-clock').textContent=value;$('minute-progress').style.strokeDashoffset=60-(s%60);$('panel-focus-task').textContent=state.target?.title||'自由专注';$('mini-title').textContent=(status==='paused'?'已暂停 · ':'')+(state.target?.title||'自由专注');$('mini-session').hidden=!active;$('focus-status').textContent=status==='running'?'把这一刻，交给眼前的事':status==='paused'?'歇一会，随时继续':'留一段时间，给一件事';$('dial-caption').textContent=status==='running'?'专注进行中':status==='paused'?'计时已暂停':'准备开始';$('choose-task').hidden=active;$('panel-timer-button').textContent=status==='running'?'暂停片刻':status==='paused'?'继续专注':'开始专注';$('panel-timer-button').disabled=requestPending||!snapshot;$('finish-button').hidden=!active;$('finish-button').disabled=requestPending;$('discard-button').hidden=!active;$('discard-button').disabled=requestPending;const sessions=snapshot?.sessions?.[todayKey()]||[];$('panel-today-total').textContent=duration(sessions.reduce((a,s)=>a+(Number(s.duration)||0),0));$('session-count').textContent=sessions.length+' 次'}
async function reload(){if(polling||requestPending)return;polling=true;const version=epoch;try{const data=await backend.getData();if(version!==epoch||requestPending)return;snapshot=data;clock.accept(data.timer);connection(true);render()}catch(e){if(version===epoch)connection(false)}finally{polling=false}}
async function saveChange(transform){if(!snapshot||requestPending)return false;const before=snapshot,scope=activeScope,key=todayKey();requestPending=true;epoch++;const next=structuredClone(snapshot);if(scope==='today')next.tasks[key]=transform(next.tasks[key]||[]);else next.goals=transform(next.goals||[]);snapshot=next;connection(true,'保存中');render();let ok=false;try{const result=scope==='today'?await backend.saveTasks(key,next.tasks[key],before.revisions?.tasks?.[key]||0):await backend.saveGoals(next.goals,before.revisions?.goals||0);if(scope==='today'){next.tasks[key]=result.items;next.revisions.tasks[key]=result.revision}else{next.goals=result.items;next.revisions.goals=result.revision}snapshot=next;ok=true;connection(true);channel.postMessage('refresh')}catch(e){snapshot=before;connection(false,'保存失败');tell(e.status===409?'其他窗口已更新任务，请确认后重试。':`保存失败，已保留原内容。${e.message||''}`)}finally{requestPending=false;epoch++;render();if(!ok)void reload()}return ok}
async function toggleDone(t){
 const target=clock.state.target,kind=activeScope==='today'?'task':'todo';
 const isRunningTarget=!t.done&&clock.state.status==='running'&&target?.id===t.id&&target.kind===kind&&(activeScope!=='today'||target.dateKey===todayKey());
 if(isRunningTarget&&!await timerAction('pause'))return;
 const done=!t.done;if(done){expandedDone=true;completingId=t.id}else completingId=null;
 if(await saveChange(arr=>arr.map(x=>x.id===t.id?{...x,done}:x))){
   if(done){document.querySelector(`[data-row-id="${CSS.escape(t.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});tell(isRunningTarget?'计时已暂停，任务完成':'又完成了一件事');channel.postMessage('completed');setTimeout(()=>{if(completingId===t.id){completingId=null;renderList(true)}},700)}
 }else{completingId=null;renderList(true)}
}
function editTask(t,copy){if(requestPending||editing)return;editing=t.id;const input=document.createElement('input');input.className='edit-input';input.value=t.text;input.maxLength=500;input.setAttribute('aria-label','编辑任务，Enter 保存，Esc 取消');copy.replaceChildren(input);input.focus();input.select();input.onclick=e=>e.stopPropagation();input.onkeydown=async e=>{if(e.isComposing)return;if(e.key==='Escape'){e.stopPropagation();editing=null;renderList(true)}if(e.key==='Enter'&&input.value.trim()){e.preventDefault();const text=input.value.trim();editing=null;const ok=await saveChange(arr=>arr.map(x=>x.id===t.id?{...x,text}:x));if(!ok){const node=[...$('panel-task-list').querySelectorAll('.task-copy')].find(x=>x.dataset.actionKey==='edit-'+t.id);if(node){editTask(t,node);node.querySelector('input').value=text}}}}}
let composing=false;$('task-input').addEventListener('compositionstart',()=>composing=true);$('task-input').addEventListener('compositionend',()=>composing=false);
$('add-form').onsubmit=async e=>{e.preventDefault();if(composing)return;const input=$('task-input'),raw=input.value,scope=activeScope;const tags=[];const text=raw.replace(/#([\u4e00-\u9fa5\w]+)/g,(_,tag)=>{tags.push(tag);return ''}).trim();if(!text||requestPending||editing)return;const t={id:crypto.randomUUID(),text,tags:[...new Set(tags)],done:false,createdAt:Date.now(),priority:'medium',...(scope==='today'?{delay_days:0,original_date:todayKey(),subtasks:[],startTime:null,endTime:null}:{type:'todo',dueDate:null,pinned:false})};input.value='';drafts[scope]='';if(!await saveChange(arr=>scope==='today'?[...arr,t]:[t,...arr])){drafts[scope]=raw;if(activeScope===scope&&!input.value)input.value=raw}};
async function timerAction(action,target=null){if(requestPending||!snapshot)return false;requestPending=true;epoch++;let ok=false;const old={...clock.state,elapsedSeconds:clock.seconds()};if(['start','pause','resume'].includes(action))clock.accept({...old,status:action==='pause'?'paused':'running',...(action==='start'?{sessionId:null,elapsedSeconds:0,target}: {})});renderTimer();try{const result=action==='start'?await backend.startTimer(target):await backend[{pause:'pauseTimer',resume:'resumeTimer',finish:'finishTimer',discard:'discardTimer'}[action]](old.sessionId);clock.accept(result.timer||result);if(action==='finish')tell(result.session?'本次专注已保存到每日记录':'计时已结束，本次不足一秒');if(action==='discard')tell('已放弃本次计时');channel.postMessage('refresh');connection(true);ok=true}catch(e){clock.accept(old);tell(e.message||'操作失败，请重试');connection(false,'操作失败')}finally{requestPending=false;epoch++;renderTimer();void reload()}return ok}
function startTask(t){selectView('focus');if(clock.state.status!=='idle'){tell('请先结束当前专注，再切换任务。');return}void timerAction('start',{kind:activeScope==='today'?'task':'todo',dateKey:activeScope==='today'?todayKey():null,id:t.id,title:t.text})}
$('panel-timer-button').onclick=()=>timerAction(clock.state.status==='running'?'pause':clock.state.status==='paused'?'resume':'start');$('finish-button').onclick=()=>timerAction('finish');
function closeDialog(){$('discard-dialog').hidden=true;$('discard-button').focus()}
$('discard-button').onclick=()=>{$('discard-dialog').hidden=false;$('cancel-discard').focus()};$('cancel-discard').onclick=closeDialog;$('confirm-discard').onclick=()=>{closeDialog();timerAction('discard')};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view));document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{if(editing){tell('先按 Enter 保存编辑，或按 Esc 取消。');return}drafts[activeScope]=$('task-input').value;activeScope=b.dataset.scope;$('task-input').value=drafts[activeScope];document.querySelectorAll('[data-scope]').forEach(x=>{x.classList.toggle('is-active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderList()});$('choose-task').onclick=()=>selectView('tasks');$('mini-session').onclick=()=>selectView('focus');$('pin-button').onclick=()=>{pinned=!pinned;$('pin-button').setAttribute('aria-pressed',String(pinned));$('pin-button').title=pinned?'取消固定':'固定面板';desktop?.setPanelPinned(pinned)};$('open-main-button').onclick=()=>desktop?.openMainWindow();$('close-button').onclick=()=>desktop?.closePanel();
document.addEventListener('keydown',e=>{if(!$('discard-dialog').hidden){if(e.key==='Escape'){e.stopPropagation();closeDialog()}if(e.key==='Tab'){e.preventDefault();(document.activeElement===$('cancel-discard')?$('confirm-discard'):$('cancel-discard')).focus()}return}if(e.key==='Escape'&&!editing)desktop?.closePanel()});
desktop?.onPanelState?.(state=>{const shell=document.querySelector('.shell');shell.classList.remove('is-opening','is-closing');void shell.offsetWidth;shell.classList.add(state.open?'is-opening':'is-closing');if(state.open){document.body.dataset.hidden='false';void reload()}});
channel.onmessage=()=>reload();document.addEventListener('visibilitychange',()=>{document.body.dataset.hidden=String(document.hidden);if(!document.hidden){renderTimer();void reload()}});
selectView('tasks');void reload();setInterval(reload,2000);setInterval(()=>{if(!document.hidden)renderTimer()},100);
